const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CV_DATA_PATH = path.join(ROOT, "data", "cv.yml");
const CV_PAGE_PATH = path.join(ROOT, "pages", "cv", "index.html");

const GENERATED_START = "<!-- CV_CONTENT_START: generated by scripts/build-cv-page.js -->";
const GENERATED_END = "<!-- CV_CONTENT_END -->";

// This parser intentionally supports only the small, human-editable YAML shape
// used by data/cv.yml. Keeping it constrained avoids adding a package manager
// requirement to this static GitHub Pages site.
function parseCvYaml(source) {
  const cv = {
    pdf: {},
    sections: [],
  };

  const lines = source.replace(/^\uFEFF/, "").split(/\r?\n/);
  let area = "";
  let currentSection = null;
  let contentTarget = null;

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    const trimmed = line.trim();

    if (contentTarget) {
      if (line.startsWith("      ")) {
        contentTarget.push(line.slice(6));
        continue;
      }

      if (!trimmed) {
        contentTarget.push("");
        continue;
      }

      contentTarget = null;
      index -= 1;
      continue;
    }

    if (!trimmed || trimmed.startsWith("#")) continue;

    if (trimmed === "pdf:") {
      area = "pdf";
      continue;
    }

    if (trimmed === "sections:") {
      area = "sections";
      continue;
    }

    if (area === "pdf") {
      const field = line.match(/^  ([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/);
      if (!field) throw new Error(`Invalid pdf field near line ${index + 1}: ${line}`);
      cv.pdf[field[1]] = parseScalar(field[2]);
      continue;
    }

    if (area === "sections") {
      const sectionStart = line.match(/^  - id:\s*(.*)$/);
      if (sectionStart) {
        currentSection = {
          id: parseScalar(sectionStart[1]),
          title: "",
          content: "",
          contentLines: [],
        };
        cv.sections.push(currentSection);
        continue;
      }

      if (!currentSection) {
        throw new Error(`Section field found before a section starts near line ${index + 1}.`);
      }

      const sectionField = line.match(/^    ([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/);
      if (!sectionField) throw new Error(`Invalid section field near line ${index + 1}: ${line}`);

      const [, key, rawValue] = sectionField;
      if (key === "content") {
        if (rawValue.trim() !== "|") {
          throw new Error(`Section content must use a literal block near line ${index + 1}.`);
        }
        contentTarget = currentSection.contentLines;
      } else {
        currentSection[key] = parseScalar(rawValue);
      }
    }
  }

  cv.sections.forEach((section) => {
    section.content = trimTrailingBlankLines(section.contentLines).join("\n");
    delete section.contentLines;
  });

  validateCv(cv);
  return cv;
}

function parseScalar(rawValue) {
  const value = rawValue.trim();
  if (!value) return "";

  if (value.startsWith('"') && value.endsWith('"')) {
    return JSON.parse(value);
  }

  if (value.startsWith("'") && value.endsWith("'")) {
    return value.slice(1, -1).replace(/''/g, "'");
  }

  return value;
}

function trimTrailingBlankLines(lines) {
  const trimmed = [...lines];
  while (trimmed.length && trimmed[trimmed.length - 1] === "") {
    trimmed.pop();
  }
  return trimmed;
}

function validateCv(cv) {
  if (!cv.pdf.href) throw new Error("data/cv.yml is missing pdf.href.");
  if (!cv.pdf.label) throw new Error("data/cv.yml is missing pdf.label.");
  if (!cv.sections.length) throw new Error("data/cv.yml does not contain any sections.");

  const ids = new Set();
  cv.sections.forEach((section, index) => {
    if (!section.id) throw new Error(`Section ${index + 1} is missing an id.`);
    if (!section.title) throw new Error(`Section ${section.id} is missing a title.`);
    if (!section.content) throw new Error(`Section ${section.id} is missing content.`);
    if (ids.has(section.id)) throw new Error(`Duplicate section id: ${section.id}`);
    ids.add(section.id);
  });
}

function renderDownloadButton(pdf) {
  return `<div class="cv-actions"><a class="cv-download-btn" href="${escapeAttribute(pdf.href)}" download>${escapeText(pdf.label)}</a></div>`;
}

function renderCvSections(sections) {
  return sections
    .map((section) => {
      return `<h2 class="cv-section-title">${section.title}</h2>\n${section.content}`;
    })
    .join("\n");
}

function renderPage(currentPage, cv) {
  const actionsStart = currentPage.indexOf('<div class="cv-actions">');
  const layoutStart = currentPage.indexOf('<div class="cv-layout">', actionsStart);
  if (actionsStart === -1 || layoutStart === -1) {
    throw new Error("Could not find the CV download action block in pages/cv/index.html.");
  }

  const withDownload = [
    currentPage.slice(0, actionsStart),
    renderDownloadButton(cv.pdf),
    currentPage.slice(layoutStart),
  ].join("");

  const generatedContent = [
    '<div class="doc-content">',
    GENERATED_START,
    renderCvSections(cv.sections),
    GENERATED_END,
    "</div></div></section></div>",
  ].join("\n");

  const contentBlockPattern = /<div class="doc-content">[\s\S]*?\r?\n<\/div><\/div><\/section><\/div>/;
  if (!contentBlockPattern.test(withDownload)) {
    throw new Error("Could not find the CV doc-content block in pages/cv/index.html.");
  }

  return withDownload.replace(contentBlockPattern, generatedContent);
}

function escapeAttribute(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeText(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function main() {
  const cvData = parseCvYaml(fs.readFileSync(CV_DATA_PATH, "utf8"));
  const currentPage = fs.readFileSync(CV_PAGE_PATH, "utf8");
  const nextPage = renderPage(currentPage, cvData);

  fs.writeFileSync(CV_PAGE_PATH, nextPage, "utf8");
  console.log(`Rendered ${cvData.sections.length} CV sections to ${CV_PAGE_PATH}`);
}

if (require.main === module) {
  main();
}
